//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utilisateurs
    {
        public int IdU { get; set; }
        public string NomPrenomU { get; set; }
        public string IdentifiantU { get; set; }
        public string EmailU { get; set; }
        public string TelU { get; set; }
        public string IdUser { get; set; }
    }
}
